[package]
name = "arc_random"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
