[package]
name = "arc"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
arc_camera = { path = "../camera" }
arc_fps = { path = "../fps" }
bevy = { workspace = true }
bevy_egui = { workspace = true }
